import { assert, demo } from "../support/index.mjs";

export async function run() {
  const drops = demo.MessageDrops.new();
  const make = (text = "hello") => demo.OwnedMessage.new(text, drops);
  const message = make();
  assert.equal(demo.consumeMessage(message), 5);
  message.dispose();
  assert.throws(() => message.length(), /disposed/);
  assert.equal(drops.count(), 1);
  assert.throws(() => demo.consumeMessageResult(make("")));
  assert.equal(drops.count(), 2);
  const duplicate = make();
  assert.throws(() => demo.consumeMessages(duplicate, duplicate), /disposed/);
  duplicate.dispose();
  assert.equal(drops.count(), 3);
  const borrowed = make();
  assert.equal(demo.borrowMessage(borrowed), 5);
  demo.mutateMessage(borrowed);
  assert.equal(borrowed.length(), 6);
  borrowed.dispose();
  assert.equal(drops.count(), 4);
  const returned = demo.returnMessage(make());
  assert.equal(returned.length(), 5);
  returned.dispose();
  assert.equal(drops.count(), 5);
  assert.equal(demo.consumeOptionalMessage(null), 0);
  assert.equal(demo.consumeOptionalMessage(make()), 5);
  assert.equal(demo.joinMessage(["a", "b"], make()), "ahellob");
  assert.equal(demo.consumeMessageWithOffset(make(), 1, 2, 3), 11);
  demo.discardMessage(make());
  const store = demo.MessageStore.new();
  await store.set(make(), new Map([["trace", "context"]]));
  assert.equal(store.count(), 6);
  store.dispose();
  const factory = demo.MessageStore.fromMessage(make());
  assert.equal(factory.count(), 5);
  factory.dispose();
  const receiver = make();
  assert.equal(receiver.combine(make()), 10);
  receiver.dispose();
  assert.equal(await demo.consumeMessageAsync(make()), 5);
  assert.equal(await demo.consumeMessagesAsync(make(), make()), 10);
  assert.equal(await demo.consumeOptionalMessageAsync(make()), 5);
  assert.equal(demo.consumeMessageWithCallback(value => value + 1, make()), 6);
  assert.equal(demo.consumeMessageBeforeCallback(make(), value => value + 1), 6);
  assert.equal(demo.consumeNamedMessage(make(), 1, 2, 3), 11);

  const beforeBorrow = drops.count();
  const retained = make();
  const cancellation = new AbortController();
  const pending = demo.holdMessage(retained, { signal: cancellation.signal });
  assert.equal(drops.borrowCount(), 1);
  assert.equal(demo.consumeMessage(retained), 0);
  retained.dispose();
  assert.equal(drops.count(), beforeBorrow);
  cancellation.abort();
  await assert.rejects(pending);
  assert.equal(drops.borrowCount(), 0);
  assert.equal(drops.count(), beforeBorrow + 1);
  retained.dispose();
  assert.equal(drops.count(), beforeBorrow + 1);
  const ownedCancellation = new AbortController();
  const owned = demo.holdOwnedMessage(make(), { signal: ownedCancellation.signal });
  ownedCancellation.abort();
  await assert.rejects(owned);
  assert.equal(drops.count(), beforeBorrow + 2);
  drops.dispose();
}
