mod attributes;
mod cfg;
mod const_expr;
mod declared_types;
mod error;
mod impl_target;
mod input;
mod items;
mod marked;
mod marker;
mod name;
mod package_graph;
mod path;
mod repr;
mod scan;
pub(crate) mod source_tree;
mod spelling;
pub(crate) mod type_expr;
mod unsupported;
mod visibility;

pub use cfg::{ActiveCfg, ConfiguredFile, RustcCfgArgs, RustcCfgArgsError};
pub use error::ScanError;
pub use input::{ScanConfiguration, ScanInput};
pub use package_graph::{ExportedPackageGraph, LoadError, LocalPackage, PackageId};
pub use scan::{PackageScan, scan, scan_file, scan_package, scan_source};
pub use source_tree::{SourceModule, SourceTree};
pub use unsupported::{UnsupportedFeature, UnsupportedInfo};

use path::{ModulePath, ModuleScope};
