//! Packages the `dart_web` (js_interop over wasm) target.
//!
//! `DartWebHost` deliberately re-derives none of the wasm build/wire/async
//! machinery — it calls straight into the already-generated, already-packed
//! `target::typescript` wasm/npm output (see `boltffi_backend::target::
//! dart_web`'s module docs). So packaging follows the same principle: this
//! runs the existing `pack wasm` pipeline unmodified to produce that
//! output, copies it next to the generated Dart file so the package is
//! self-contained, and adds exactly one new piece of its own — a small JS
//! loader script that instantiates the wrapped module and republishes its
//! exports under the global name every `@JS()` extern in the generated
//! Dart file expects (see `DartWebHost::js_namespace`).

use std::fs;
use std::path::Path;

use boltffi_backend::target::dart_web::DartWebHost;

use crate::{
    cli::{CliError, Result},
    commands::{
        generate::{GenerateOptions, GenerateTarget, run_generate_with_output},
        pack::{PackDartWebOptions, PackWasmOptions, pack_wasm},
    },
    config::{Config, WasmNpmTarget},
    reporter::Reporter,
};

pub(crate) fn pack_dart_web(
    config: &Config,
    options: PackDartWebOptions,
    reporter: &Reporter,
) -> Result<()> {
    if !config.is_dart_web_enabled() {
        return Err(CliError::CommandFailed {
            command: "targets.dart_web.enabled = false".to_string(),
            status: None,
        });
    }
    if !config.wasm_npm_targets().contains(&WasmNpmTarget::Web) {
        return Err(CliError::CommandFailed {
            command: "targets.dart_web requires \"web\" in targets.wasm.npm.targets \
                      (the generated Dart file calls into that browser entrypoint)"
                .to_string(),
            status: None,
        });
    }

    reporter.section("🕸️", "Packing Dart Web");

    // `DartWebHost` wraps target::typescript's wasm/npm output wholesale
    // rather than re-deriving any of the build/strip/optimize/transpile
    // pipeline — so packaging it is exactly `pack wasm`, unmodified,
    // plus the Dart-specific steps below.
    {
        let step = reporter.step("Packing wrapped WASM/TypeScript module");
        pack_wasm(
            config,
            PackWasmOptions {
                execution: options.execution.clone(),
            },
            reporter,
        )?;
        step.finish_success();
    }

    let module_name = config.dart_web_module_name();
    let namespace = DartWebHost::new(&module_name)
        .map_err(|error| CliError::CommandFailed {
            command: format!("dart_web module name '{module_name}' is invalid: {error}"),
            status: None,
        })?
        .js_namespace();

    let output_directory = config.dart_web_output();

    if options.execution.regenerate {
        let step = reporter.step("Generating Dart bindings");
        run_generate_with_output(
            config,
            GenerateOptions {
                target: GenerateTarget::DartWeb,
                output: Some(output_directory.clone()),
                experimental: options.experimental,
                cargo_args: options.execution.cargo_args.clone(),
                deny_skipped: options.execution.deny_skipped,
            },
        )?;
        step.finish_success();
    }

    let npm_output_directory = config.wasm_npm_output();
    let vendored_npm_directory = output_directory.join("npm");

    {
        let step = reporter.step("Vendoring the wrapped WASM/JS module");
        copy_directory_contents(&npm_output_directory, &vendored_npm_directory)?;
        step.finish_success();
    }

    {
        let step = reporter.step("Generating the JS loader");
        let loader_path = output_directory.join(format!("{module_name}_web_loader.mjs"));
        let loader_source = render_loader_script(&namespace);
        fs::write(&loader_path, loader_source).map_err(|source| CliError::WriteFailed {
            path: loader_path.clone(),
            source,
        })?;
        step.finish_success();
    }

    reporter.finish();
    Ok(())
}

/// The one piece of JS this target actually hand-generates: it
/// instantiates `target::typescript`'s already-compiled `web.js` entry
/// (auto-fetching the wasm binary) and republishes its exports plus a
/// readiness `Promise` under the two globals the generated Dart file's
/// `@JS()` externs and `init()` function expect — see
/// `DartWebHost::js_namespace` / `render::Module::ready_global` in
/// `boltffi_backend::target::dart_web`, which this must stay in sync
/// with exactly.
fn render_loader_script(namespace: &str) -> String {
    format!(
        "// Generated by `boltffi pack dart-web`. Do not edit by hand.\n\
         //\n\
         // Load this script (as an ES module) before the compiled Dart\n\
         // output — e.g. from index.html:\n\
         //   <script type=\"module\" src=\"{module}_web_loader.mjs\"></script>\n\
         //   <script defer src=\"main.dart.js\"></script>\n\
         import * as __boltffiModule from \"./npm/web.js\";\n\n\
         globalThis[\"{namespace}\"] = __boltffiModule;\n\
         globalThis[\"{namespace}_ready\"] = __boltffiModule.initialized;\n",
        module = namespace.trim_start_matches("__boltffi_"),
    )
}

fn copy_directory_contents(from: &Path, to: &Path) -> Result<()> {
    walkdir::WalkDir::new(from)
        .into_iter()
        .try_for_each(|entry| {
            let entry = entry.map_err(|error| {
                let path = error
                    .path()
                    .map(Path::to_path_buf)
                    .unwrap_or_else(|| from.to_path_buf());
                let source = error
                    .into_io_error()
                    .unwrap_or_else(|| std::io::Error::other("directory walk failed"));

                CliError::ReadFailed { path, source }
            })?;

            if !entry.file_type().is_file() {
                return Ok(());
            }

            let relative =
                entry
                    .path()
                    .strip_prefix(from)
                    .map_err(|source| CliError::ReadFailed {
                        path: entry.path().to_path_buf(),
                        source: std::io::Error::other(source.to_string()),
                    })?;
            let dest = to.join(relative);

            if let Some(parent) = dest.parent() {
                fs::create_dir_all(parent).map_err(|source| CliError::CreateDirectoryFailed {
                    path: parent.to_path_buf(),
                    source,
                })?;
            }

            fs::copy(entry.path(), &dest).map_err(|source| CliError::CopyFailed {
                from: entry.path().to_path_buf(),
                to: dest,
                source,
            })?;
            Ok(())
        })
}
