pub(crate) fn render_runtime_sources_source(entries: &[(String, String)]) -> String {
    let mut generated =
        String::from("/// Generated by boltffi_cli/build.rs from runtime/typescript/src.\n");
    generated.push_str("/// Do not edit by hand — this file does not exist in the source tree.\n");
    generated.push_str("pub const RUNTIME_SOURCES: &[(&str, &str)] = &[\n");
    for (name, embedded_path) in entries {
        generated.push_str(&format!(
            "    ({name:?}, include_str!({embedded_path:?})),\n"
        ));
    }
    generated.push_str("];\n");
    generated
}

#[cfg(test)]
mod tests {
    use super::render_runtime_sources_source;

    #[test]
    fn renders_one_include_str_entry_per_file_in_order() {
        let source = render_runtime_sources_source(&[
            ("callback.js".to_string(), "/out/callback.js".to_string()),
            ("index.js".to_string(), "/out/index.js".to_string()),
        ]);

        assert!(source.contains("pub const RUNTIME_SOURCES: &[(&str, &str)] = &["));
        assert!(source.contains("(\"callback.js\", include_str!(\"/out/callback.js\")),"));
        assert!(source.contains("(\"index.js\", include_str!(\"/out/index.js\")),"));
        assert!(
            source.find("callback.js").unwrap() < source.find("index.js").unwrap(),
            "entries must render in the order they were given"
        );
    }

    #[test]
    fn escapes_file_names_and_paths_that_need_it() {
        let source = render_runtime_sources_source(&[(
            "weird name.js".to_string(),
            "C:\\out\\weird name.js".to_string(),
        )]);

        assert!(
            source.contains("(\"weird name.js\", include_str!(\"C:\\\\out\\\\weird name.js\")),")
        );
    }

    #[test]
    fn renders_an_empty_array_for_no_entries() {
        let source = render_runtime_sources_source(&[]);

        assert!(source.contains("pub const RUNTIME_SOURCES: &[(&str, &str)] = &[\n];\n"));
    }
}
